# Generated by Django 4.0.3 on 2022-05-03 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('nivel', models.IntegerField()),
                ('disponibilidad', models.BooleanField()),
                ('descripcion', models.CharField(max_length=150)),
                ('imagen', models.ImageField(null=True, upload_to='Fotos_Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('imagen', models.ImageField(null=True, upload_to='Fotos_Institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.IntegerField(null=True)),
                ('genero', models.CharField(max_length=6)),
                ('imagen', models.ImageField(null=True, upload_to='Fotos')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('materiales', models.FileField(null=True, upload_to='')),
                ('descripcion', models.CharField(max_length=300)),
                ('Envio_Tare', models.FileField(null=True, upload_to='')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiSalud.curso')),
            ],
        ),
    ]
