# Generated by Django 4.0.3 on 2022-05-03 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MiSalud', '0002_tipo_persona_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MiSalud.institucion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MiSalud.persona'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MiSalud.institucion'),
            preserve_default=False,
        ),
    ]
