# Generated by Django 4.0.3 on 2022-05-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiSalud', '0003_curso_institucion_curso_tipo_persona_institucion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='tipo',
        ),
        migrations.AddField(
            model_name='curso',
            name='persona',
            field=models.ManyToManyField(to='MiSalud.persona'),
        ),
    ]
