# Generated by Django 4.0.3 on 2022-05-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiSalud', '0004_remove_curso_tipo_curso_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='calificacion',
            field=models.IntegerField(null=True),
        ),
    ]
